// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(fn, interval) {
    var pending;
    pending = false;
    return function() {
      var args, that;
      args = arguments;
      that = this;
      if (!pending) {
        pending = true;
        return setTimeout(function() {
          pending = false;
          return fn.apply(that, args);
        }, interval);
      }
    };
  };

}).call(this);
